### ISSUE TITLE
Can't see most ship models

### ISSUE THREAD

**Issue by mjones329** [tjakubo2/TTS_xwing#11]
Hi, I'm new to TTS and the X-wing mod. I am having a problem with ship models showing up.  I have subscribed to recommended content, and pasted the chest set up files into the TTS folder on my Mac, but every time I try to spectate or play a game, I get a ton of errors and almost none of the ship models show up . I see cards for pilots, etc, just no ships - with the exception of TIE fighters; they seem to show up. Any ideas?

**Comment by tjakubo2** [comment]
What's the error you're getting, and are these appearing when you use the zip file from #10?

**Comment by mjones329** [comment]
14077438:SSL routine ssl23 GET_SERVER_HELLO:tlsv1 alert internal error.

Is that what you need? 

The error does not happen on the zip file from #10, but when I try to spawn any ships from my chest, I cannot see most of the ships (a couple work - tie fighters, millennium falcons, and a couple others.) When I try to spawn ships, I get error messages and a continuous drip of pixels dropping from the top off the screen.  As mentioned.  I do see the cards for the pilots, etc, though.

**Comment by tjakubo2** [comment]
This is the same issue as #10. You are getting errors cause TTS on Mac has problems with https links. It's not X-Wing specific, [see here](http://www.berserk-games.com/forums/showthread.php?2628-Linux-amp-OSX-make-requests-for-assets-via-SSLv3-and-fail). When playing your own game, you can use stuff without https link, but you can't do anything about other people stuff when spectating. On the bottom of the bug report thread I linnked you are some workaround by setting up a proxy on your computer but TTS-side it's a dead end.

**Comment by tjakubo2** [comment]
Forgot to close, continue discussion at #10.
