### ISSUE TITLE
Kaa'to Leeachos not found

### ISSUE THREAD

**Issue by gonkun** [tjakubo2/TTS_xwing#14]
Squadron Builder doesn't found Kaa'to Leeachos miniature.

**Comment by tjakubo2** [comment]
Hey gonkun, provide the list snippet you pasted in game when that happened and I'll have it fixed right away.

**Comment by tjakubo2** [comment]
Fixed in https://github.com/tjakubo2/TTS_xwing/commit/d632187851aa2e2fda63b492ade219dac889fa46
