### ISSUE TITLE
Millenium Falcon Sengors Loop

### ISSUE THREAD

**Issue by ImTheRhino** [tjakubo2/TTS_xwing#18]
This card gets replaced with the original evade title card.

Cheers

**Comment by tjakubo2** [comment]
When there are many cards bearing the same name (Millenium Falcon, R2-D2 etc.), they are spawned as a multi-state object. Right click spawned card, select "Set State" and choose the one you want. You can then right click it again and choose "Reset" to make it only current version permanently (removing other states).
