### ISSUE TITLE
IG-88A issue in Squad Builder

### ISSUE THREAD

**Issue by Malignence** [tjakubo2/TTS_xwing#22]
Super quick and easy fix, when loading a Scum squad from geordanr IG-AA Pilots are named using the syntax IG-88(a-d) And in the mod the syntax is IG88-(a-d) which returns an unrecognized pilot loading the squad. Manually changing the syntax in the notebook parse fixes it.

**Comment by tjakubo2** [comment]
Thanks for the info, it's actually xwing-builder.co.uk "fault", Geordanr has the version that appears on cards :)

Sadly I already deleted my partial work (save) on that *twice*, jesus. I'll have this updated today though.
