### ISSUE TITLE
All IG-88 dials show "IG" as pilot name.

### ISSUE THREAD

**Issue by Elavion** [tjakubo2/TTS_xwing#23]
It's a minor thing, but it makes it slightly difficult to figure out which dial is which, since they mostly run in pairs.

**Comment by tjakubo2** [comment]
Hey, I see that it can be annoying, but I just checked and they got correctly named in my game. Could you try and re-do the steps and tell me very much click by click how to reproduce it? It could be some deeper bug when parsing from specific builders or something (which shouldn't happen but this spaghetti did worse before). So far I've tried few times and their dials do show the full name on hover.

You could also check and see if you have this game auto-saved if that was your last one.

Cheers!

**Comment by Elavion** [comment]
https://youtu.be/4nXLX7Spgso
I was using the http://xwing-builder.co.uk builder.

**Comment by tjakubo2** [comment]
Oh wow, you mean that name! I totally though you mean the one you get when mousing over a dial in your zone, sorry, I'm dumb.

I'll have that fixed asap.
