### ISSUE TITLE
Fail to load images

### ISSUE THREAD

**Issue by NecrontyrBDN** [tjakubo2/TTS_xwing#25]
When I start the module, there are several error messages when loading images. I can not see the damage mallets at first. When loading squadrons some are blank, both pilots and dials. Improvements and talents included.

I have tried to restart the program and delete / add the module several times without solution

**Comment by tjakubo2** [comment]
Hey, unfortunately stuff loads for me at the moment, so it's not as easy as dead link. 

Try doing that:
1. Untick the "Mod caching" in Menu -> Configuration
2. Delete all the stuff in Documents\My Games\Tabletop Simulator\Mods\Images (bunch of images)
and then load the mod.

If stuff will still not load up, pinpoint one thing that doesn't (any deck, model, whatever) and let me know exactly what it is. We'll take a look at its asset links.

**Comment by tjakubo2** [comment]
If you decide to let me know how this went, reopen this issue. All the assets are 100% up and accesible.

**Comment by NecrontyrBDN** [comment]
It works 100% thanks you
