### ISSUE TITLE
List from Yet Another X Wing Squad Builder fails to load

### ISSUE THREAD

**Issue by Lettuceman44** [tjakubo2/TTS_xwing#27]
The given squad fails to load from the squad spawner

Squad should load from the squad spawn

1. Load game
2. Press Squad Builder
3.Press Initialize
4. Paste list in the spawn me note card

> [b]Poe Dameron (PS9) (33)[/b]
> [i]Push the Limit (3)[/i]
> [i]BB-8 (2)[/i]
> [i]Primed Thrusters (1)[/i]
> [i]Integrated Astromech (0)[/i]
> [i]Black One (1)[/i]
> 
> [b]Biggs Darklighter (25)[/b]
> [i]R2-D2 (4)[/i]
> [i]Integrated Astromech (0)[/i]
> 
> [b]Jess Pava (25)[/b]
> [i]M9-G8 (3)[/i]
> [i]Pattern Analyzer (2)[/i]
> [i]Integrated Astromech (0)[/i]
> 
> [b][i]Total: 99[/i][/b]

5.Press Spawn it
6. Put it in the notebook
7.Press parse notebook
8. Message "Ship model 'Push the Limit' not found... Stop
**Does this still occur after saving & loading game:**
Yes

**Comment by tjakubo2** [comment]
Hey Lettuceman44, please remember that you have to copy the *whole* thing from BB-code box on the builder. An easy way is to just hit the "Copy" button, but if you're selecting manually, all the list must be copied (including the url at the end). Here's the pic on that from docs: http://i.imgur.com/XDG4eeb.png

So if your paste snippet is actually
```
[b]Poe Dameron (PS9) (33)[/b]
[i]Push the Limit (3)[/i]
[i]BB-8 (2)[/i]
[i]Primed Thrusters (1)[/i]
[i]Integrated Astromech (0)[/i]
[i]Black One (1)[/i]

[b]Biggs Darklighter (25)[/b]
[i]R2-D2 (4)[/i]
[i]Integrated Astromech (0)[/i]

[b]Jess Pava (25)[/b]
[i]M9-G8 (3)[/i]
[i]Pattern Analyzer (2)[/i]
[i]Integrated Astromech (0)[/i]

[b][i]Total: 99[/i][/b]

[url=http://geordanr.github.io/xwing/?f=Rebel%20Alliance&d=v4!s!196:18,-1,148,203:39:20:;4:-1,3:-1:20:;199:-1,206,204:-1:20:&sn=Unnamed%20Squadron&obs=]View in Yet Another Squad Builder[/url]
```
it should work fine. Please confirm if you were able to get it to work :)

**Comment by Lettuceman44** [comment]
Welp I feel foolish now. That indeed works.

Sorry about that.

**Comment by tjakubo2** [comment]
No prob. I can see how this may be confusing, but spawner needs that last bit to identify Geordanr builder format. Sadly other builders *can* include BB-code in list title/description, so I can't rely on just [b]/[i] tags present in the snippet. Cheers!
