### ISSUE TITLE
Clicking "move" and "undo" too quickly breaks things.

### ISSUE THREAD

**Issue by jbuckland** [tjakubo2/TTS_xwing#3]
On a dial, if you click move then undo quickly, the dial will be back in the "Move" state, but the ship will not go back to it's original position. This leaves your ship and dial in a "broken" state. 

A possible solution might be to disable "undo" until "move" in completed.

**Comment by tjakubo2** [comment]
Stuff should now be aware if command got through or failed. This is dangerous cause if something goes wrong with making the object ready again it will be stuck forever, but there's no other clean way to do it I think.

I wonder if referencing commits here works, addresed with cd0cb46e61f93926cde4ac54256e6884a5d27c43. Maybe short works too cd0cdb46.
