### ISSUE TITLE
CURRENTLY IN DEVELOPMENT

### ISSUE THREAD

**Issue by tjakubo2** [tjakubo2/TTS_xwing#32]
- [x] Wookie gunship expansion (FabioOtto doing his magics)
- [ ] Hotkeys for revealing a dial, moving, performing actions and tasks (ruler, template etc)  
- [x] Range 1, 2, 3 (separate) rulers for checking range (no arc lines)  
- [x] Range rulers that only show ship arc (contextually spawned for ships that have specific arc types)  
- [ ] Full template-obstacle overlap detection  
- [ ] "Ready"/"Still planning" notification system (not mandatory to use)
- [x] (optional, not sure yet) Nubs collision detection
- [ ] Ship to ship range check
- [ ] (request) Kallus token

If you want to suggest specifics about these, feel free to chime in - for example which key combinations should do what (we only have 10 keys to assign to), how overlaps should be communicated to player etc.

There's no ETA on any of these. More complex things could take more than few weeks to figure out and even more time to flesh out. Please be patient (you can help to speed it up too!).

**Comment by Elavion** [comment]
First of all, I wanted to thank you for all the awesome work you've put into this mod :) . You really improved it already.

Here's some feature ideas, no sweat if you don't want to/ don't have time for them:

1. This is probably too complex, but it would be nice to have the ability to spawn a range ruler touching ship A pointed at ship B for checking TL- the way it works right now (with the R tool) it's giving you a lot of extra information about range that you're not supposed to get from a TL (measurements to other ships and obstacles)
2. This might be an easier temporary workaround for the nubs thing- what if there was a button for moving the ship backwards a millimeter or so, to adjust it's position?
3. thicker and/or outlined obstacles- right now it's sometimes tricky to figure out if the ship is overlapping or not.

**Comment by tjakubo2** [comment]
Hey Elavion!

About 1:  
It's not that complex, really. The biggest problem so far was how to actually implement it interface-wise. Same command in both ships description? Typing in other ship name? Everything coming to mind is just clunky and hacky to implement. BUT, with the recently added hotkeys (I'm passing around a testing table, hit me up if ya want to try it), this is actually doable in a reasonable way. Totally a thing to add to the list.

About 2:  
I used to avoid nubs collision cause it would take some boring tinkering to add (debugging in TTS is  a nightmare).... but with the recent update Physics class, it should be a piece of cake (same class is what made templte-obstacle and ship-obstacle collision detection possible). So on the list and probably could come sooner than other things as long as Physics turns out to be reliable enough.

About 3:  
I swear I messed with them few times already. Each rock has a scale-setting script on itself that was adjusted like 3 times. It looked OK, then its micrometer obstacle fest again. Maybe TTS has problems with non-uniform scaling and we just need to re-do the obstacle models.  
BUT if the overlap detection will come (and I'm pretty sure I can strap it together), this would be much less of an issue. Since (re)modelling is a nightmare for me, I think I'll do the detection first :)

Thanks for the feedback, I really appreciate it. It's nice knowing what other players want and not just add random things that come to mind :)

**Comment by Elavion** [comment]
Oh, one more thing I forgot to mention- it would be awesome if you could spawn a squadron by pasting a link to it, it would also solve the issue of too long squadlists.

now to answer to your answer (heh)

Perhaps pressing the TL button could spawn a button on every other ship in the game?
If I understand correctly that you're asking me for help with testing some features, sure, why not :)


Hyped for the nubs and overlaps, those are some great news :)

**Comment by tjakubo2** [comment]
These two, however, are troublesome. 

To identify a squad from a link, we have to decipher these number into pilots/upgrades names. Since TTS doesn't allow scripts to communicate with the internet, it would have to be all included internally.... whole XWS spec database (I think link numbers are based on it). It can be done but would take some effort to literally re-write the thing in Lua. Goes way down the priority queue unless someone helps on that.

About dynamic buttons (created on various objects from one object script) - I messed around creating buttons on ships way back when figuring out dial assignment system, turns out it is quite unreliable. TTS always had problems with buttons - being removed for no reason, NOT removed when they should have been, weird ghost buttons out of nowhere. Trying to avoid "dynamic" buttons as much as I can.

**Comment by Elavion** [comment]
The bit about script connecting is interesting, never thought about that (though I guess it makes sense). Perhaps some workaround using the tablet would be possible?

Dynamic buttons suck, got it. How about using a slider-based solution then? TL spawns an arrow that you rotate around the base, and once it's set it spawns a ruler in that direction.

**Comment by DylanFahey** [comment]
Ship-to-ship range is one of the things I personally want the most. Ideally drawn as a line from the closest point on one ship to the closest point on another ship. I think this would be hugely helpful for checking obstacles and obstructed shots, since the actual range ruler is difficult to use for this, and the line tool is hard to line up accurately in 3d.

**Comment by tjakubo2** [comment]
Having problems with nubs collisions. There's no way to visualize or properly debug TTS Physics cast functions so its just shooting blind for now. Will try to fiddle with ships colliders too.

**Comment by tjakubo2** [comment]
**Coming very soon (2-3 days, need to be at my PC):** Range Ruler Options That Actually Make Sense, featuring:

*(for each base size)*
 - Range 1+2+3 circles (all at once, no arc lines) for range checks  
 - Range 1/2/3 circle (any one of these, no arc lines) for range checks  
 - Primary arc only  
 - Primary + side arc only  
 - Primary + back arc only
 - (currently implemented, stays as) Omni-ruler for turrets

Each of these will have its own command. Soon to be integrated with hotkeys and ship-to-ship range checking.

**Comment by tjakubo2** [comment]
Add two days to above. Bleh.

**Comment by tjakubo2** [comment]
Distinct range ruler added. Wiki will be soon updated.

**Comment by tjakubo2** [comment]
Bomb drop assist added. Wasn't on the list, but it came out decent.

**Comment by tjakubo2** [comment]
Nubs collisions and ship <-> obstacle overlap detection added.

**Comment by Elavion** [comment]
I love how this thread is basically a newsletter at this point :P

You're doing a great work bud.

P.S. Was about to ask for bomb assist, thanks!

**Comment by tjakubo2** [comment]
Moved all this to a roadmap on which I want to keep order.
