### ISSUE TITLE
Auzituck Gunship range tool does not have the 180 degree arc line

### ISSUE THREAD

**Issue by Elavion** [tjakubo2/TTS_xwing#33]
**What happened:** no arc line for for arc indicator (r command)

**What was supposed to happen:** party bus-esque line

Picture for reference:

![untitled](https://user-images.githubusercontent.com/27161457/27012493-c151279a-4ed0-11e7-8a33-1ea628f1cafa.png)

**Comment by tjakubo2** [comment]
Daamn, of course I forgot that. Have it done though so will update later today, thanks for the info!
