### ISSUE TITLE
Issue spawning Tarn Mison

### ISSUE THREAD

**Issue by DylanFahey** [tjakubo2/TTS_xwing#34]
I get the following error when trying to spawn Tarn Mison using the Squad Builder. 

>**Error B12**
>(Unkown 'Tarn Mison' model ship type)

The model and the pilot reference card still spawn, but the shield tokens, ship reference card, and dials do not spawn. If you try to assign a dial, an error pops up:

>**Quick Assign:** Some ship models in your zone have not been recognized. Make sure your models are sourced from squad building tray on this table and contact author if this issue persists

This error can be reproduced quite easily using this list (made using xwing-builder.co.uk):

` Tarn Mison (23) 3 3 2 3 2`

**Comment by tjakubo2** [comment]
Thanks for the info, this will be resolved soon!
