### ISSUE TITLE
Mobile Arc token conflicts with Assign Dial button

### ISSUE THREAD

**Issue by JohnnyCheese** [tjakubo2/TTS_xwing#35]
When Spawning any pilot for the Lancer Pursuit Craft, the ship comes with the Mobile Arc Token on its base.

When you put the ship on the secret area to set the dials and press the Assign Dials button, the Mobile Arc Token will prevent the dials to be set.. 
Is there a way to make the Assign Dials button ignore the Mobile Arc Token?

**Comment by tjakubo2** [comment]
Yes, of course. That's a dumb interaction, I'll have it sorted out.

**Comment by tjakubo2** [comment]
Just a chime in: fix for this issue has a side effect of ships getting locked after they have their dials assigned. This is not intended but minor enough to not be on the top of my priority list so you just have to hit L over them to proceed. Will be fixed soon, just not right away (trying to think of an elegant solution).
