### ISSUE TITLE
Little things to be done ATM

### ISSUE THREAD

**Issue by tjakubo2** [tjakubo2/TTS_xwing#36]
- [x] "Slave I" title spawning error  
- [ ] Ships not locking after assigning dials   
- [ ] Some kind of deleted dials handling?  
- [x] Make expaned buttons set default on a dial
- [x] Wider slide button

**Comment by JohnnyCheese** [comment]
Is it posssible so set a slider on Taon Rolls, like the barrel roll slider?

**Comment by tjakubo2** [comment]
Slide button should work on everything that slides, including Talon Rolls. Just tried, did a Talon Roll, clicked Slide and it worked, let me know if it wouldn't for you for some reason :)

BTW I was supposed to make Slide button lil wider, thanks for touching on that.

**Comment by tjakubo2** [comment]
Stuff added to present roadmap.
