### ISSUE TITLE
Switch back to old collision on ship bases?

### ISSUE THREAD

**Issue by NotShadowFever** [tjakubo2/TTS_xwing#38]
I usually play X Wing on TTS without any automated movement and lining up movement templates is harder with the new collision affecting nubs. 

Is it possible to add a command to switch the ship collider back to the old box shaped version?

**Comment by tjakubo2** [comment]
I've created a thing for you to do that:
http://steamcommunity.com/sharedfiles/filedetails/?id=969347207

Save the dominoes to your chest and spawn in game when you want to use it. I wanted a command, but switching object properties is (from the technical side) destroying and re-creating it, and doing that mid command processing messed it up.

Please let me know if that fits your purpose :)

**Comment by NotShadowFever** [comment]
This is brilliant. Thank you so much

**Comment by tjakubo2** [comment]
Feel free to reopen this if any related issues arise, have fun :)
