### ISSUE TITLE
Squad Builder Not Spawning Units

### ISSUE THREAD

**Issue by Jakiro91** [tjakubo2/TTS_xwing#40]
I got a success message when I copy/pasted form x-wingbuilder.co.uk but nothing spawned.

My squad was suppose to spawn but did not.

![20170710221930_1](https://user-images.githubusercontent.com/30064643/28049632-3d0ea4f8-65be-11e7-9ed4-6d7afd388941.jpg)
![20170710221935_1](https://user-images.githubusercontent.com/30064643/28049633-3f99592a-65be-11e7-9799-b37ec445c6b5.jpg)

Still occurs after saving, reloading, etc

**Comment by tjakubo2** [comment]
Hey, remember you should copy the whole snippet side provides you, not just the part that has pilots. Best to click the "Copy to keyboard" button like guide instructs to: http://i.imgur.com/oNoJgLX.png

The list should spawn fine if you do that, please confirm here if you get it to work :)
