### ISSUE TITLE
Adding automove/autobump/list spawning events to the timeline

### ISSUE THREAD

**Issue by lhayhurst** [tjakubo2/TTS_xwing#43]
Hi, I recently created a timeline of X-wing tech, had a couple entries in there for you, but am missing some of your bigger milestones. Do you have the dates and a short blurb of each milestone handy?

https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=16EjZfL8d_J6fCYb2w0ekyAaVzgv-xBIpp4SlW87N4Ro&font=Default&lang=en&initial_zoom=2&height=650

There's a google sheet I'll add them too that powers the timeline. 

Nice work on TTS!!
--sozin

**Comment by tjakubo2** [comment]
This mod is a small part of the X-Wing history on TTS. I'm not _that_ old, but it would be something like

---

_March 2015_
[Complete Collection](https://steamcommunity.com/sharedfiles/filedetails/?id=415295765) mod on Workshop, first place to centralize assets (models, cards, tokens and such)

_February 2016_
Dedicated [playing table by Korean Templar](https://steamcommunity.com/sharedfiles/filedetails/?id=631304247) (not the first or last, but this one was good and gained traction)

_March 2016_
First version of automated movement on TTS (by Hera Vertigo)

_April 2016_
First version of automated squad builder (by dzikakulka)

_May 2016_
First version of overlap detection on TTS (by Hera Vertigo and Flolania)

_September 2016_
Table script re-done (by dzikakulka, based on all the previous work), first release (on GitHub)

_February 2017_
[Unified mod](http://steamcommunity.com/sharedfiles/filedetails/?id=862644552) launch with it's GitHub wiki to get all the pieces together (by dzikakulka)

_March 2017_
[Beautiful dedicated models](http://steamcommunity.com/sharedfiles/filedetails/?id=894280761) (by FabioOtto) made Unified asset-complete and keep it up to date afterwards

_(... development continues ...)_

---

Tho by looking at the list now, it really doesn't do the justice. There was and still are _many, many_ awesome people involved ([even just in the current thing](https://github.com/tjakubo2/TTS_xwing/wiki/Credits)), it was and is still done step by step in small increments. Hard to distinguish milestones, features are generally deployed in small portions.

But anyway, feel free to hack it up and adapt to your thing, very cool idea indeed :)

**Comment by tjakubo2** [comment]
I guess we got that sorted.
