### ISSUE TITLE
Firing Arcs

### ISSUE THREAD

**Issue by ImTheRhino** [tjakubo2/TTS_xwing#47]
**What happened:**
Some people with ships such as the Defender,when clicking the Arc button, they get their firing arc facing out the rear

**What was supposed to happen:**
Firing arc from the front.

**How to make the issue happen:**
Unsure. Only seems to happen to the visitor, not the host.

**Does this still occur after saving & loading game:**
Have not trried that yet.

**Comment by tjakubo2** [comment]
If it's visible one way for some players and another way for other players, it's not mod related. We can't set positions of stuff just for some, desync like that should simply never happen. I've also noticed this, there's already a few topics about most recent TTS update doing stuff like that:

http://www.berserk-games.com/forums/showthread.php?4555-Pointer-desync-with-online-games
http://www.berserk-games.com/forums/showthread.php?4479-P2P-Errors

**Comment by ImTheRhino** [comment]
Cheers mate.

Keep up the good work.

**Comment by tjakubo2** [comment]
Latest TTS update claims:

> **Fixes**
>  -- Fixed issue with scripted movement of an object not always syncing to clients.

I'll leave this issue up for a week or two more, please let me know if any of this still persists in TTS v9.9 - if something looks wrong, screenshot and post here.

**Comment by tjakubo2** [comment]
There were reports on Discord. Looks like we wait for a fix again.

**Comment by tjakubo2** [comment]
Yet another update that claims to fix desync:
http://www.berserk-games.com/forums/showthread.php?4750-Update-v10-0-New-Networking-Updated-Main-Menu-Viticulture-DLC-expansions!

I think this issue should be simply forwarded to Berserk forums if it resurfaces. They've been working on networking so could use the info.
