### ISSUE TITLE
Issue with rulers when not the host. (Also reloading the game issue)

### ISSUE THREAD

**Issue by SkeletonPuns** [tjakubo2/TTS_xwing#48]
Not sure if this has happened to other people before but it seems to be a lot more common recently. 

Whenever I'm in someone else's game the toggle rulers button seems to spawn rulers that bug out and not display correctly. Only 4 of the 8 rulers during obstacle placement are positioned right and the other 4 are incorrectly shown parallel to the others. It also happens with the place forces rulers as the side ones are also horizontal. It is a lot more common in higher ping rooms but even with green ping it happens more often then not recently. It doesn't seem to be shown from the hosts point of view either as it happened to someone else in a game I was hosting and they were all shown correctly on my computer.

Its not a big deal seeing as you can easily guess where the other rulers should be based on the ones that are correct and most of the time they can be fixed by locking and unlocking them but its an issue none the less.

As a side note another thing happens when reloading the game in another persons server where the mats don't appear and it can usually be fixed by rejoining. 

All this seems to be on the latest release.

**Comment by tjakubo2** [comment]
It's the same desync as #47.

**Comment by SkeletonPuns** [comment]
Just read that on there. Oh well, in any case its not much of a problem as its easily able to be worked around.

**Comment by tjakubo2** [comment]
This may be possibly fixed, refer to #47.
