### ISSUE TITLE
Movement template not spawning

### ISSUE THREAD

**Issue by Patperk88** [tjakubo2/TTS_xwing#49]
When you select a maneuver and hit the "T" button to spawn a template, it will often not appear.

**Comment by tjakubo2** [comment]
Does that ever happen when you're the host or at least it does not appear for everyone on the table? Take a look at #48 #47

**Comment by JohnnyCheese** [comment]
I have the same issue, but as #47 and #48, the host sees it..

**Comment by tjakubo2** [comment]
The host sees the template spawn? Or the host also observes this issue?

**Comment by JohnnyCheese** [comment]
the host sees the template

**Comment by Patperk88** [comment]
I believe the problem has only occurred when I wasn't the host.

**Comment by tjakubo2** [comment]
So it's the same desync as #47, #48

**Comment by tjakubo2** [comment]
This may be possibly fixed, refer to #47.
