### ISSUE TITLE
TTS crashes for connected client when "remove" buttons are clicked

### ISSUE THREAD

**Issue by smathson** [tjakubo2/TTS_xwing#5]
First off, just want to say thanks for all your hard work with this mod. It's really impressive how much automation you've been able to build into this thing. Great job!

Just played a game with the latest TTS (v8.0) and had consistent crashes as the connected client (not host) whenever I tried to click a "remove" button on certain pieces. Movement dials were the most consistent. Every time I completed a movement and then clicked the "Delete" button, TTS would crash. If the host clicked the delete button, the movement piece would return to the auto-dials in my hidden zone but the buttons would still be on the movement piece. In every case after a crash I was able to reconnect and continue playing the game using manual movements and no auto-dials.

I also crashed a few times (although not every time) when the host clicked the remove button on some pieces. This one wasn't consistent so I wasn't able to determine a pattern but pretty sure it happened a handful of times when the host was trying to remove the range indicator.

Crash logs all reported the error as Write access violations. I've got error logs and crash dumps if those would help, just let me know.

**Comment by tjakubo2** [comment]
This looks like issue with buttons for clients (removing them specifically) that jut got lot worse in v8.0. Few updates back, obj.clearButtons() stopped working ([example thread](http://www.berserk-games.com/forums/showthread.php?2897-In-not-my-serever-self-clearButtons()-doesn-t-work)), but adopting another method for clearing buttons (but = obj.getButtons() then obj.removeButton(index) for each one in the table) worked around it.

Sadly, now it just crashes with no Lua-related error. Worst thing is, it did work OK before v8.0 and still works for host, so not only reproducing and testing is a nightmare but also all we can do is blind changes in code until it clicks hopefully. I'll drop a bug report too but they kinda abandoned scripting a while ago, didn't even keep docs or atom plugin up to date.

**Comment by tjakubo2** [comment]
Confirmed to be a general TTS issue:
http://www.berserk-games.com/forums/showthread.php?2958-Game-crash-on-(presumably)-removing-a-button-v8-specific

**Comment by smathson** [comment]
Thanks for looking into this so quickly. Let me know if there is anything I can do to help. Really strange that they haven't made scripting a higher priority in support or testing since in my mind the mod community is what is really driving the popularity of the game.

**Comment by tjakubo2** [comment]
TTS hotfix online, props to [Knils](https://github.com/Knils) for a [quick reaction](http://www.berserk-games.com/forums/showthread.php?2958-Game-crash-on-(presumably)-removing-a-button-v8-specific&p=13255#post13255), seems like he had to break calculator to reduce RPC count but saved a lot of mods in no time :)
This could also mean that other unpredictable client behaviour like obj.clearButtons() or some sync issues are fixed so good day for TTS!
