### ISSUE TITLE
Tie Aggressor Reference card

### ISSUE THREAD

**Issue by JohnnyCheese** [tjakubo2/TTS_xwing#51]
The tie Aggressor maneuver reference card is showing the Lambda Shuttle reference card

**Comment by tjakubo2** [comment]
Thanks for the report, Ill have it added next release :)

**Comment by tjakubo2** [comment]
For some reason this was not done even tho I have the asset https://i.imgur.com/ccQOBnS.jpg

**Comment by tjakubo2** [comment]
Merging with #58.
