### ISSUE TITLE
Missing Content

### ISSUE THREAD

**Issue by JohnnyCheese** [tjakubo2/TTS_xwing#55]
Not exactly sure if this is the apropriate channel, but here it is

As of today, the mod has all cards and ships until wave11, including G4H pack.

It is missing revealed content from waves 12 and 13, wich have already been revealed/spoiled

This is a compilation of all upgrades, pilots and dials wich still haven´t been implemented

Hope this helps!

**Upgrade Cards:**

Trajectory Simulator (system)
https://images-cdn.fantasyflightgames.com/filer_public/26/ce/26ce168b-93fa-4f38-8301-4d991cac4e37/swx67-trajectory-simulator.png

Deflective Plating (mod)
https://images-cdn.fantasyflightgames.com/filer_public/06/22/062205d2-690a-4a85-8dca-95a369cd6c94/swx67-deflective-plating.png

Crossfire Formation (title)
https://images-cdn.fantasyflightgames.com/filer_public/fb/32/fb323bf4-6067-4dff-bd41-5b1424f0c100/swx67-crossfire-formation.png

Advanced Optics (tech)
https://images-cdn.fantasyflightgames.com/filer_public/5b/4a/5b4aa788-a2db-466a-89d5-4b3e39d1e61c/swx67-advanced-optics.png

Ordnance Silos (bomb)
https://images-cdn.fantasyflightgames.com/filer_public/08/0b/080beb95-7d79-4760-b471-ebd2fc2d0c34/swx67-ordnance-silos.png

Rattled (condition)
https://images-cdn.fantasyflightgames.com/filer_public/25/6b/256b74be-0770-4d6a-aa54-759668788161/swx67-rattled.png

Ghost v2 (title)
https://images-cdn.fantasyflightgames.com/filer_public/63/db/63db3b47-6fe4-42f1-aae8-b97f17dc0bbe/swx72-ghost.png

Phantom 2 (title)
https://images-cdn.fantasyflightgames.com/filer_public/8f/b4/8fb44367-0e64-4606-b62a-b82b834be9a7/swx72-phantom-ii.png

Maul (crew)
https://images-cdn.fantasyflightgames.com/filer_public/a9/1d/a91d8e63-ee2f-45f3-8b28-cc5073270bf3/swx72-maul.png

Courier Droid (crew)
https://images-cdn.fantasyflightgames.com/filer_public/e0/c5/e0c509e8-a69a-4f76-91c0-018a0f7be539/swx72-courier-droid.png

Chopper (astromech)
https://images-cdn.fantasyflightgames.com/filer_public/c6/e6/c6e6779c-8e3c-4a1d-bb44-0a8164babd53/swx72-chopper.png

Flight Assist Astromech (astromech)
https://images-cdn.fantasyflightgames.com/filer_public/b3/2d/b32d0c24-3566-4ba5-8d1c-a8d29fde667f/swx72-flight-assist-astromech.png

Contraband Cybernetics (ilicit)
https://images-cdn.fantasyflightgames.com/filer_public/17/2a/172a5999-cd2e-4bc8-a21c-1d1cf9d6ce7d/swx70-contraband-cybernetics.png

Enforcer (title)
https://images-cdn.fantasyflightgames.com/filer_public/2a/1d/2a1d7f86-f65c-438a-8d72-b3198d4d5d40/swx70-enforcer.png

XG1 Assault configuration (title)
https://images-cdn.fantasyflightgames.com/filer_public/e8/f3/e8f3c87a-59c7-49f1-8260-dbbddd54497c/swx69-xg-1-assault-configuration.png

OS1 Arsenal Loadout (title)
https://images-cdn.fantasyflightgames.com/filer_public/e8/f3/e8f3c87a-59c7-49f1-8260-dbbddd54497c/swx69-xg-1-assault-configuration.png

Jamming Beam (cannon)
https://images-cdn.fantasyflightgames.com/filer_public/1e/9f/1e9fe1c6-b12d-407e-8e60-22f2bb6646c3/swx69-jamming-beam.png

Linked Battery (cannon)
https://images-cdn.fantasyflightgames.com/filer_public/2b/2c/2b2c69d7-558b-4499-a543-60dbc9ba9b02/swx69-linked-battery.png

Saturation Salvo (elite)
https://images-cdn.fantasyflightgames.com/filer_public/0d/7c/0d7c5231-8777-457a-b37e-92dd415a4280/swx69-saturation-salvo.png

R5 TK (scum astromech)
https://photos-5.dropbox.com/t/2/AABVYZeiBsgMlgmxP24iOvx6C28l02Z-unPq8Kpn69Ml9Q/12/8602105/png/32x32/1/_/1/2/r5%20tk.PNG/EMmmswYY8OwCIAIoAg/0c_wEqNb_o6LN7bbq4IkQ7_60YcKHxs2G3jxSUu47NU?size=2048x1536&size_mode=3

Scrambler Missiles (missile)
https://photos-4.dropbox.com/t/2/AAAeLkpS0qltBm6cCN_qlb03wdzsr_RgExiSvL92lZPs9A/12/8602105/png/32x32/1/_/1/2/scramble%20missiles.PNG/EMmmswYY8OwCIAIoAg/snrC_fIxR377GR9zxWwftUoz6ngQ8IBD9eWojgPu7KE?size=2048x1536&size_mode=3

Pilots:

Nu Squadron Pilot (gunboat)
https://images-cdn.fantasyflightgames.com/filer_public/05/52/05525d95-f15a-4719-a6c4-b6e18b754d9a/swx69-nu-squadron-pilot.png

Rho Squadron Veteran (gunboat)
https://images-cdn.fantasyflightgames.com/filer_public/83/51/83519b09-682f-454d-b429-5240881850c1/swx69-rho-squadron-pilot.png

Liutenant Karsabi (gunboat)
https://images-cdn.fantasyflightgames.com/filer_public/cf/7a/cf7abc34-b094-40af-928e-9b5a3696837b/swx69-lieutenant-karsabi.png

Major Vynder (gunboat)
https://images-cdn.fantasyflightgames.com/filer_public/32/86/32860740-51f3-426b-ab80-595c8caf9af4/swx69-major-vynder.png

Crimson Squadron Pilot (resistence bomber)
https://photos-2.dropbox.com/t/2/AADDuUQcgB7A5DqLFAE10N15AaD2kvMUIOE3lbueXvVBdA/12/8602105/png/32x32/1/_/1/2/crimson%20squadron%20pilot.PNG/EMmmswYY8ewCIAIoAg/2Gsy2uqT2G-lQuvxdojIEk1Gnu-b-cECvle4L6aD1uQ?size=2048x1536&size_mode=3

Crimson Specialist (Resistence Bomber)
https://images-cdn.fantasyflightgames.com/filer_public/93/1b/931bfe74-cf58-4ae8-b6cf-11050bcfa81d/swx67-crimson-specialist.png

Cobalt Leader
https://photos-1.dropbox.com/t/2/AABr2BcGrPBngHnsrP6Lf9dRFcnIHQXXa0DZP1J1EcF4eg/12/8602105/png/32x32/1/_/1/2/cobalt%20leader.PNG/EMmmswYY8OwCIAIoAg/bU_-pQOPc1W785e7WPiaXO1YWJWQeR8d4wvcurlHrOA?size=2048x1536&size_mode=3

Crimson Leader (Resistence Bomber)
https://images-cdn.fantasyflightgames.com/filer_public/62/92/6292687b-d973-45c2-9405-21b51058549f/swx67-crimson-leader.png

AP5 (Phantom 2)
https://images-cdn.fantasyflightgames.com/filer_public/12/92/129299da-fdef-4c3b-96d8-06c23270de7e/swx72-ap-5.png

Zeb (Phantom 2)
https://images-cdn.fantasyflightgames.com/filer_public/7f/a1/7fa11f94-35f1-4e35-bd37-6860f302976c/swx72-zeb-orrelios.png

Ezra Bridger (Phantom 2)
https://images-cdn.fantasyflightgames.com/filer_public/17/da/17da06c9-3b61-4060-bc6d-5dc1b589a0c7/swx72-ezra-bridger.png

Fenn Rau (Phantom 2)
https://images-cdn.fantasyflightgames.com/filer_public/50/78/5078c5e4-b6ca-4203-abfc-d4ed4752749b/swx72-fenn-rau.png

Cartel Brute (Kimogila)
https://images-cdn.fantasyflightgames.com/filer_public/b5/3a/b53ada87-4b50-4a18-94cc-183f6b3565ef/swx70-cartel-brute.png

Cartel Executioner (Kimogila)
https://photos-5.dropbox.com/t/2/AACIjZUoSB_DGYFcbe_Vp3yP66vCkptncDKoS4G3MGjjDA/12/8602105/png/32x32/1/_/1/2/cartel%20executioner.PNG/EMmmswYY8OwCIAIoAg/psx7tivWPa4kbjCL7QV2ilGIpuOynXVf9ONc7n3oUhI?size=2048x1536&size_mode=3

Dalan Oberos (Kimogila)
https://images-cdn.fantasyflightgames.com/filer_public/19/b3/19b3a603-f973-4064-ab69-fdf72f6d79e8/swx70-dalan-oberos.png

Torani Kulda (Kimogila)
https://images-cdn.fantasyflightgames.com/filer_public/23/8d/238d3ebc-519d-4593-884b-3379d72e5f60/swx70-torani-kulda.png

Kylo Ren (silencer)
https://images-cdn.fantasyflightgames.com/filer_public/d8/dc/d8dcd8fb-cea8-41a2-8c3f-3bebc631d1a0/swx68-kylo-ren.png

Dials:

Phantom II Dial
https://photos-6.dropbox.com/t/2/AACU6wXg9UGInRzLuqQ-z_iZnDQbzVH2CkiRbbeJyDSFxg/12/8602105/png/32x32/1/_/1/2/PHANTOM%202%20DIAL.PNG/EMmmswYY8ewCIAIoAg/YK7EHeE8rPO_3meDIBYVFDv234Xcd0CUXvJRdxM0Xvk?size=2048x1536&size_mode=3

Resistence Bomber Dial
https://photos-4.dropbox.com/t/2/AADHU97M9ew7DG4IF9FDAEePTmZlDPa6pQ-JQTYnykIA0A/12/8602105/png/32x32/1/_/1/2/resistance%20bomber%20dial.PNG/EMmmswYY8OwCIAIoAg/EMSwRpHRjBdau6WI3a8CsC83XqDdLDXWT8PslrQwTx8?size=2048x1536&size_mode=3

Gunboat Dial
https://images-cdn.fantasyflightgames.com/filer_public/40/0b/400bd56b-4bb9-4046-a5b3-2575f7a40088/swx69_maneuver_dial.png

Kimoglia Dial
https://scontent.fcgh9-1.fna.fbcdn.net/v/t1.0-9/23755587_2296290860387793_5714014071438485627_n.jpg?oh=cccf21faa1ac0989f20db6be5e11ca8d&oe=5AA6F25F

**Comment by tjakubo2** [comment]
This helps A LOT. Thanks a ton, I'm quite busy lately. I'll be adding those cards ASAP, probably in a batch next monday. We still lack models for new ships though :(

**Comment by JohnnyCheese** [comment]
I think Fabio Otto has made a kimogila model, I will talk to him..

I found this stuff though

https://star-wars.aminoapps.com/page/blog/modeling-a-3d-tie-silencer/0NFk_uKaj784r6Vx83E0xKVW250rdM

https://steamcommunity.com/sharedfiles/filedetails/?id=619682365

We could try contacting these guys and ask them to use their models

**Comment by tjakubo2** [comment]
@JohnnyCheese The dropbox links aren't working for me (images not set to public visibilty?) :( If they do contain images of quality better than this: https://vignette.wikia.nocookie.net/xwing-miniatures/images/a/a4/R5TK_sneak.JPG/revision/latest?cb=20171123091543
I'd prefer making cards with them :)

**Comment by JohnnyCheese** [comment]
@tjakubo2 yah, use them, I did the same thing, snatched them from the unboxing video, they are on the same quality..

**Comment by tjakubo2** [comment]
Should be all in in 1.1.43. Let me know if anything more is missing. Huge thanks to Smight and Voiceoftheforce on those.
