### ISSUE TITLE
BUG with Nym in x-wing TTS

### ISSUE THREAD

**Issue by arquimagoazul** [tjakubo2/TTS_xwing#56]
Whem i was plaing x-wings in TTS, a bug happened.
![sem titulo](https://user-images.githubusercontent.com/33972243/33226722-145ee196-d173-11e7-8b70-4a79e420f493.png)
The Nym's dial don't work. The game turn off.

**What happened:**

**What was supposed to happen:**

**How to make the issue happen:**

**Does this still occur after saving & loading game:**

**Comment by tjakubo2** [comment]
Clear your cache, restart TTS, verify game files if it still won't work. It's just a deck of images from my side. Anything that crashes a game is a problem of TTS itself. Scripts could *hang* the game for a bit, but crashing like that is a different thing.

**Comment by tjakubo2** [comment]
I guess this was resolved on gave up on. Reopen if you have any news on the issue.
