### ISSUE TITLE
Tie Silencer Talon Rolls

### ISSUE THREAD

**Issue by ImTheRhino** [tjakubo2/TTS_xwing#57]
**What happened:**
Ship rotates incorrectly doing Talon Roll
**What was supposed to happen:**
Different rotation
**How to make the issue happen:**
Execute Talon Roll
**Does this still occur after saving & loading game:**
Yes
![20180103081848_1](https://user-images.githubusercontent.com/25953269/34502437-31c29e8e-f05f-11e7-934c-17acd7a23d88.jpg)

**Comment by tjakubo2** [comment]
Thumbs up for a proper report!
Fixed in 1.1.44
