### ISSUE TITLE
Ezra/Sheathipede Maneuver Card and Dial wrong

### ISSUE THREAD

**Issue by OverlordEris** [tjakubo2/TTS_xwing#60]
The maneuver reference card for the Ezra on the Sheathipede shows the K-wing. Additionally, the dial does not appear to work properly. When I pull the dial card out from the dial token there is not "Lay out" option, it has to be done manually. Thanks for all your hard work on this!!!

**Comment by OverlordEris** [comment]
Okay...I'm a newbie. The auto generate dial from placing your ship in your "area" appears to work fine, it is just the dial and reference card from the list spawn that doesn't appear to work correctly (not that you need it).

**Comment by tjakubo2** [comment]
Yeah, refcards are a pain to work with since TTS does not support single cards (gotta do manual save edits). For now they're K-Wing duds. If someone needs a reference on how a ship moves at the moment, laying out its dials on the side is a workaround :)
