### ISSUE TITLE
"Snap" Wexlrey uses wrong image on ship's base

### ISSUE THREAD

**Issue by Sandrem** [tjakubo2/TTS_xwing#61]
**What happened:**
"Snap" Wexley -  his ship's base has wrong image - string "Red Ace" instead of "Snap" Wexley

**What was supposed to happen:**
Ship's base must have string "Snap" Wexley instead of "Red Ace"
I attached correct image for this pilot (text is generated in Strange Eons): ![snapwexleyfixed](https://user-images.githubusercontent.com/6347443/36000805-d1df6282-0d2c-11e8-904d-3fa713c94b98.png)

**How to make the issue happen:**
Load pilot "Snap" Wexley using squad builder.

**Does this still occur after saving & loading game:**
Yes

**Comment by tjakubo2** [comment]
Thanks Sandrem, we get a fair bit of that since most new wave stuff that doesn't require new models is done by incompetent people like me :)

**Comment by tjakubo2** [comment]
Added ion 1.1.45
