### ISSUE TITLE
Objects not loading

### ISSUE THREAD

**Issue by leoarthur83** [tjakubo2/TTS_xwing#62]
Hi, friends. The models and many objects are not loadind. Messages "WWW Model Error: Couldn't connect to server" are exhibited several times. The Squad Build Tray load like a mess. And a Custom Model window are continnualy exhibited. Please, see the images. I clicked a lot on import button, but many objects don't load even so.

That problem appeared in my notebook with Windows 10. In my desktop PC with Windows 7 everything is OK.

Do you have some solution?

Thanks and congratulations for the great job!

![error](https://user-images.githubusercontent.com/36453423/36168571-ace4cabe-10e0-11e8-9e90-ab4a7e446399.png)

![error2](https://user-images.githubusercontent.com/36453423/36168572-ad1b5552-10e0-11e8-96f7-6c13629ca82d.png)

**Comment by tjakubo2** [comment]
Try disabling your antivirus and firewall (temporarily), if it loads try to look up how to add an exception. It would be great if you had the ability to check if it loads on a different network (e.g. through a connected mobile via tethering).

If stuff still won't work, you can download a package of all the assets to be placed in TTS cache so it doesn't download them (but that's not guaranteed 100% of things), join the Discord server on instructions how to do that, pinned message in #general channel.

**Comment by leoarthur83** [comment]
You were right. It was antivirus and firewall protction. I will configure approprialy the protections and will add the exception. Just to inform, the problem doesn't appear in my Windows 7.

Thank you very much.

**Comment by tjakubo2** [comment]
Happy to hear this was resolved :)
