### ISSUE TITLE
Medium bases fall through the table after dials assigned

### ISSUE THREAD

**Issue by TLFJ** [tjakubo2/TTS_xwing#64]
**What happened:**
Medium bases fall through the table after dials assigned, if you unlock them.

U-wing, reaper, and firesprays.

You know - medium bases.

**What was supposed to happen:**
They were supposed to work. They instead fell through the table. Endlessly.

Even if you managed to grab it, and lock it, the moment it was unlocked, it’s fall through the table.

**How to make the issue happen:**

Spawn a dial for a medium base. The ship will get locked on top of the dials, in the way, and when you unlock it to move it, it falls through the table.

**Does this still occur after saving & loading game:**
Yes

**Comment by tjakubo2** [comment]
What would be en example of medium base ship? Fill the actual form in how
to reproduce it.

**Comment by tjakubo2** [comment]
TIE Reaper is a small base ship, Firespray and U-Wing are large base. This mod is for original X-Wing, not 2.0.

Like if asking for a proper report is snide lol. If you would incude details to begin with (like proper reproduction steps: spawn squad with this snippet, move those ships, click assign dials), there would be no misunderstanding. Now I'm being snide for a reason and you should learn to relay info in a useful way.

**Comment by JohnnyCheese** [comment]
Thats actually my fault.. the 2.0 mod still links to this github for help and etc.. sorry for the trouble!

The medium base collider link is missing, will correct it asap

**Comment by tjakubo2** [comment]
That's fine Johnny, I'm just having some problems at school and whatnot and this ticket caught me in a really shitty mood :D
