### ISSUE TITLE
No scripting buttons?

### ISSUE THREAD

**Issue by tmdesigned** [tjakubo2/TTS_xwing#66]
**What happened:**

I am new to TTS, but it seems to run smoothly. However I am missing the buttons shown in the getting started tutorial. Attached is a screenshot of the squad building tray.

**What was supposed to happen:**
I believe there are supposed to be some white buttons and notes on this area.

**How to make the issue happen:**
I loaded the module, picked a color, and zoomed over to the squad building tray.

**Does this still occur after saving & loading game:**
Yes, I created several new games.

I am on a Mac if that matters. Version is 1.1.48

![screen shot 2018-09-16 at 7 05 59 pm](https://user-images.githubusercontent.com/3608018/45601998-19b87080-b9e4-11e8-83b7-acf2d723bfde.jpg)

**Comment by tjakubo** [comment]
Hey, what OS version are you on? I've seen identical issues with TTS on MacOS and it was unsupported OS version, see this bug report on official forums: http://www.berserk-games.com/forums/showthread.php?5132-Buttons-will-not-load-when-loading-a-table

If your OS is up to date or there's no way for you to update, I can prepare a little test save with just one button. If that will also not show up properly, it means it's some underlying TTS/MacOS issue I cannot fix from scripting (and it should be reported as TTS bug).

PS. Thanks for including all the info, that's a nice report to look at :)

**Comment by tmdesigned** [comment]
Ahh! That must be it. I am on the same OS version (Yosemite, 10.10.5). I will upgrade in a day or two and check back in. 

I work for a software company. If we don't precisely follow the bug report format, the issue gets sent back to us. :)

Thanks for the quick response.

**Comment by tjakubo** [comment]
Any info on how that went @tmdesigned ?

**Comment by tjakubo** [comment]
Closing that for now then, reopen if neccesary,
