### ISSUE TITLE
List importer not working.

### ISSUE THREAD

**Issue by Bobylein** [tjakubo2/TTS_xwing#67]
The list import function as descipted here in the wiki is not working for the new edition list makers, even not for https://raithos.github.io/ which seems to use the old geonardir code.

**Comment by tjakubo** [comment]
This builder you linked is for X-Wing 2.0, this mod is for original version of X-Wing. There's a 2.0 fork of this mod on the workshop (should be easy to find, something around "Unified X-Wing 2.0"). If you would have a 1.0 list builder snippet that doesn't work, feel free to post it here reopening the issue.
