### ISSUE TITLE
Pilot Cards Missing...

### ISSUE THREAD

**Issue by DrDanielJackson** [tjakubo2/TTS_xwing#69]
Hi guys,

The majority of Pilot cards seem to be blank in the 1.0 version.

I don't think they are loading the images correctly from wherever they're hosted.

Cheers,
Dr Daniel Jackson

**What happened:**
90% of Pilot card fronts are blank (Just to confirm this is in Unified X-Wing mod 1.0 for TTS)
**What was supposed to happen:**
They should have a picture of the Pilot card and info on them.
**How to make the issue happen:**
Load the card from any source, Sqaud builder, collection etc.
**Does this still occur after saving & loading game:**
Yes

**Comment by tjakubo** [comment]
Reuploaded a bunch of geekdo/picload hosted images in the new version. Please reopen this issue if there would be still any images missing or some just changed were borked.
