### ISSUE TITLE
'A' Commands not work

### ISSUE THREAD

**Issue by Warklaw** [tjakubo2/TTS_xwing#70]
**What happened:**
Trying to enter any of the 'A' (Arc) commands into the description field, and nothing happens.

**What was supposed to happen:**
I would hope to see the corresponding ARC appear on the ship.

**How to make the issue happen:**
Just enter an 'a' command in description and execute.

**Does this still occur after saving & loading game:**
Yes.

[TS_Save_2.txt](https://github.com/tjakubo2/TTS_xwing/files/2631103/TS_Save_2.txt)

**Comment by tjakubo** [comment]
Hey, the save you linked is from the [Unified 2.0 mod](https://steamcommunity.com/sharedfiles/filedetails/?id=1386600664), not from [the mod this repo holds](http://steamcommunity.com/sharedfiles/filedetails/?id=862644552) :)

AFAIK they've changed some commands for 2.0 adaptation, try posting at the xxx-2_0 channels on the official Discord.
