### ISSUE TITLE
Consider using TTSModManager

### ISSUE THREAD

**Issue by argonui** [tjakubo2/TTS_xwing#75]
Hi there,

I think your Mod would be a good candidate for using the tool i've just released: https://github.com/argonui/TTSModManager. Instead of just storing your luascript, you can store your entire mod in source control: all objects, lua, xml, etc

Let met know if you'd be interested in exploring this usage!

**Comment by tjakubo** [comment]
Hey, this repo' mod is discontinued as FFG moved on to X-Wing 2.0/2.5. Code/wiki is there mostly for archival reasons, assets are down and it's pretty much unplayable on TTS for a few years already.
