### ISSUE TITLE
Movements are not accurate

### ISSUE THREAD

**Issue by Hacofried** [tjakubo2/TTS_xwing#8]
Nice for a stright and koiogran movements. 

Turn movements: Large base ships moves as little base ships when turn (at least 3 speed movements); and little base ships moves far as rule indicates, only a little but far than real...In 2 speed turns they are more accurate but not at all in large ships bases but the same for little ships bases. They moves good in speed 1 movements for large ships, not for little ships bases they displace their movements more to the direction where they must to turn (left or right). 

Bank movements: The same for banked movements but little base ships move shorter than the related speed and a bit too much to the direction of the movement. In 2 bank speed moves the right speed but a bit too much to the direction of the bank (for little and big base ships). In bank 1 speed large base ships moves shorter and a bit too much to the opposite direction of the movement (bank left to the right and bank right to the left), in little base ships the movement is shorter than the speed and displacement a bit too much to the direction of the bank.

I don't try special movements like segnor or tallon.

**Comment by tjakubo2** [comment]
How did you measure the moves? 

Because the templates are WRONG:
See here: http://imgur.com/a/3mFxP
When flipped over and layed one over another, they are not symmetrical. Which means they are skewed and not actually fit for proper movement measurement. 

The only reference should be a ship base length. I can list you the movement offsets in milimeters (taking small base as 40mm) and you can compare it to how do you think they should move.

**Comment by Hacofried** [comment]
I measured palcing a 1 stright to indicate where a small base ship must to
be when it do the movement and 2 stright for larga base ship. After i
marked the true position i writted the command for movement and ships are
not where them must to be...

There are another issue or bug in vcx and scum firesprays created after
this monday, their ruler and autobump detector are like they have an small
base. You need fix this first.

Thx for all sorry for my bad english.

**Comment by tjakubo2** [comment]
About the other issue, yeah, sorry, list spawner now gets you correct models (right link on them) so they work out of the box.

About this, how do you know that "ships are not where them must to be"? How do you measure a position where they should be?

**Comment by Hacofried** [comment]
Because i placed first the ship in the start and in the end of the movement
rule (f.e. 3 turn), then i placed a rule to mark the position and then i
made the movement.
If you want we can create a game and try?

**Comment by tjakubo2** [comment]
Please try making a screenshot. And keep in mind what I said before, use ship base as the measurement reference (or straight templates at most as they look kinda ok).

**Comment by Hacofried** [comment]
Ok but is better if we create a game in tts and we look the problem.

**Comment by tjakubo2** [comment]
I guess this was cleared up then. I also double chceckd the values in singleplayer and they do conform to these: 

> Range in mm: 100.0, 200.0, 300.0
> Base size in mm: 40.0, 80.0
> Straight in mm: 40.0, 80.0, 120.0, 160.0, 200.0
> Turn inside radii in mm: 25.0, 53.0, 80.0
> Turn outside radii in mm: 45.0, 73.0, 100.0
> Bank inside radii in mm: 70.0, 120.0, 170.0
> Bank outside radii in mm: 90.0, 140.0, 190.0
(source: [one](https://boardgamegeek.com/thread/1337514/dimensions-radii-and-arc-lenghts-maneuver-template), [two](https://teamcovenant.com/general/the-road-to-4-6-0-and-better-firing-arcs))

When using a 40mm small base as a measuring reference.

I'll be happy to reopen this and add any tweaks in the code if any discrepancies will surface but please do provide a clear explanation on what and when goes wrong.
